name: deploy to webserver

on:
  push:
    branches-ignore:
      - dev
      - build
    paths:
      - '*'
  pull_request:
    branches-ignore:
      - dev
      - build
    paths:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: build, deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setting up NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install closure-compiler
        run: sudo npm i -g google-closure-compiler

      - name: execute pull on server
        if: github.ref == 'refs/heads/master'
        run:
          curl https://lff.l3p3.de/server/git/gitPull.api
